# Generated by Django 3.2.5 on 2021-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smallVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=80, null=True)),
                ('make', models.CharField(default=None, max_length=80, null=True)),
                ('model', models.CharField(default=None, max_length=80, null=True)),
                ('type', models.CharField(default=None, max_length=80, null=True)),
                ('plate', models.CharField(default=None, max_length=80, null=True)),
                ('vin', models.CharField(default=None, max_length=80, null=True)),
                ('ezPass', models.CharField(default=None, max_length=80, null=True)),
                ('mileage', models.CharField(default=None, max_length=80, null=True)),
                ('reportedProblem', models.CharField(default=None, max_length=80, null=True)),
                ('inspection', models.CharField(default=None, max_length=80, null=True)),
                ('registration', models.CharField(default=None, max_length=80, null=True)),
                ('oilChange', models.CharField(default=None, max_length=80, null=True)),
                ('isMonitored', models.CharField(default=None, max_length=80, null=True)),
                ('status', models.CharField(default=None, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=80, null=True)),
                ('make', models.CharField(default=None, max_length=80, null=True)),
                ('model', models.CharField(default=None, max_length=80, null=True)),
                ('type', models.CharField(default=None, max_length=80, null=True)),
                ('plate', models.CharField(default=None, max_length=80, null=True)),
                ('vin', models.CharField(default=None, max_length=80, null=True)),
                ('ezPass', models.CharField(default=None, max_length=80, null=True)),
                ('mileage', models.CharField(default=None, max_length=80, null=True)),
                ('reportedProblem', models.CharField(default=None, max_length=80, null=True)),
                ('inspection', models.DateField(default=None, null=True)),
                ('registration', models.DateField(default=None, null=True)),
                ('oilChange', models.CharField(default=None, max_length=80, null=True)),
                ('isMonitored', models.CharField(default=None, max_length=80, null=True)),
                ('status', models.CharField(default=None, max_length=80, null=True)),
            ],
        ),
    ]
