# Generated by Django 3.2.5 on 2021-10-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallvehicles',
            name='inspection',
            field=models.DateField(default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='registration',
            field=models.DateField(default=None, max_length=80, null=True),
        ),
    ]
