# Generated by Django 3.2.8 on 2021-10-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20211007_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=80)),
                ('address', models.CharField(default=None, max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='trucks',
            name='type',
            field=models.CharField(choices=[('SEDAN', 'sedan'), ('PICKUP', 'PICKUP'), ('SUV', 'suv')], default='Sedan', max_length=80, null=True),
        ),
    ]
