# Generated by Django 3.2.8 on 2021-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20211014_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallvehicles',
            name='insurance_card',
            field=models.ImageField(default='default.jpg', upload_to='static/insurance_cards'),
        ),
        migrations.AddField(
            model_name='smallvehicles',
            name='title',
            field=models.ImageField(default='default.jpg', upload_to='statics/title_pics'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='insurance_card',
            field=models.ImageField(default='default.jpg', upload_to='static/insurance_cards'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='title',
            field=models.ImageField(default='default.jpg', upload_to='statics/title_pics'),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='isMonitored',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Pickup', 'Pickup'), ('SUV', 'SUV')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='isMonitored',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Pickup', 'Pickup'), ('SUV', 'SUV')], default=None, max_length=80, null=True),
        ),
    ]
