# Generated by Django 3.2.5 on 2021-10-19 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20211018_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='permits',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permits',
            name='type',
            field=models.CharField(choices=[('Fire Hydrant', 'Fire Hydrant'), ('Parking', 'Parking'), ('Boom', 'Boom')], default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='insurance_card',
            field=models.ImageField(default='default.jpg', upload_to='Inventory/static/insurance_cards'),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='oilChange',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='title',
            field=models.ImageField(default='default.jpg', upload_to='Inventory/static/title_pics'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='insurance_card',
            field=models.ImageField(default='default.jpg', upload_to='Inventory/static/insurance_cards'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='oilChange',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='title',
            field=models.ImageField(default='default.jpg', upload_to='Inventory/static/title_pics'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Pickup', 'Pickup'), ('SUV', 'SUV'), ('Flatbed', 'Flatbed')], default=None, max_length=80, null=True),
        ),
    ]
