# Generated by Django 3.2.5 on 2021-10-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20211019_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallvehicles',
            name='insurance_card',
            field=models.ImageField(default='default.jpg', upload_to='media/insurance_cards/'),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='title',
            field=models.ImageField(default='default.jpg', upload_to='media/title_pics/'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='insurance_card',
            field=models.ImageField(default='default.jpg', upload_to='media/insurance_cards/'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='title',
            field=models.ImageField(default='default.jpg', upload_to='media/title_pics/'),
        ),
    ]
