# Generated by Django 3.2.8 on 2021-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20211021_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallvehicles',
            name='insurance_card',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_cards/'),
        ),
        migrations.AlterField(
            model_name='smallvehicles',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='title_pics/'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='insurance_card',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_cards/'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='title_pics/'),
        ),
    ]
